### ISSUE TITLE
Make checkboxes and radiobuttons styles on iOS browsers and IE11 consistent with proper browsers.

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#497]
iOS has a higher priority of course

**Comment by MartijnR** [comment]
* [ ] styles in iOS
* [ ] padding and column layout in iOS
* [ ] check FF, Chrome, Edge, IE11
* [ ] styles in IE11

**Comment by MartijnR** [comment]
IE11 approach (with regressions): 

```scss
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
    input[type=radio], 
    input[type=checkbox]{
        opacity: 0;
        + .option-label::before {
            display: inline-block;
            content: '';
            vertical-align: middle;
            width: 20px;
            height: 20px;
            margin-left: -30px;
            margin-right: 10px;
            margin-bottom: 0;
            margin-top: 0;
            border-width: 3px;
            border-style: solid;
            background-color: transparent;
        }
    }
    input[type=checkbox] + .option-label::before {
        border-radius: 0;
        @include checkbox-unchecked-style;
    }
    input[type=checkbox]:checked + .option-label::before {
        @include checkbox-checked-style;
    }
    input[type=radio] + .option-label::before {
        border-radius: 10px;
        @include radio-unchecked-style;
    }
    input[type=radio]:checked + .option-label::before {
        @include radio-checked-style;
    }
    input[type=checkbox]:focus,
    input[type=radio]:focus {
        + .option-label::before {
            @include focus-shadow;;
        }
    }
    input[type=checkbox]:disabled,
    input[type=checkbox][readonly],
    input[type=radio]:disabled,
    input[type=radio][readonly]{
        + .option-label::before{
            @include disabled-radiocheck-style;
        }
    }
}
```
